In [15]:
import pandas as pd
import numpy as np


df = pd.read_csv("../data/whoop_fitness_dataset_100k.csv")

df

,user_id,date,day_of_week,age,gender,weight_kg,height_cm,fitness_level,primary_sport,recovery_score,...,activity_strain,avg_heart_rate,max_heart_rate,activity_calories,hr_zone_1_min,hr_zone_2_min,hr_zone_3_min,hr_zone_4_min,hr_zone_5_min,workout_time_of_day
0,USER_00001,2023-01-01,Sunday,56,Female,53.9,167.2,Beginner,Weight Training,57.8,...,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
1,USER_00001,2023-01-02,Monday,56,Female,53.9,167.2,Beginner,Weight Training,62.6,...,7.47,121.2,137.6,371.0,11.9,18.0,15.9,11.6,4.6,Evening
2,USER_00001,2023-01-03,Tuesday,56,Female,53.9,167.2,Beginner,Weight Training,81.5,...,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
3,USER_00001,2023-01-04,Wednesday,56,Female,53.9,167.2,Beginner,Weight Training,55.0,...,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
4,USER_00001,2023-01-05,Thursday,56,Female,53.9,167.2,Beginner,Weight Training,62.5,...,15.27,136.4,152.8,623.0,3.7,6.0,13.7,18.6,9.0,Evening
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,USER_00286,2023-05-13,Saturday,50,Female,58.9,153.9,Intermediate,Running,100.0,...,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
99996,USER_00286,2023-05-14,Sunday,50,Female,58.9,153.9,Intermediate,Running,63.7,...,19.76,150.5,167.5,696.0,0.4,6.6,10.2,16.6,10.2,Evening
99997,USER_00286,2023-05-15,Monday,50,Female,58.9,153.9,Intermediate,Running,83.1,...,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
99998,USER_00286,2023-05-16,Tuesday,50,Female,58.9,153.9,Intermediate,Running,81.4,...,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
99999,USER_00286,2023-05-17,Wednesday,50,Female,58.9,153.9,Intermediate,Running,62.2,...,12.88,136.6,153.6,557.0,5.4,10.5,13.5,17.1,7.5,Morning

In [13]:
df.columns

Index(['user_id', 'date', 'day_of_week', 'age', 'gender', 'weight_kg',
       'height_cm', 'fitness_level', 'primary_sport', 'recovery_score',
       'day_strain', 'sleep_hours', 'sleep_efficiency', 'sleep_performance',
       'light_sleep_hours', 'rem_sleep_hours', 'deep_sleep_hours', 'wake_ups',
       'time_to_fall_asleep_min', 'hrv', 'resting_heart_rate', 'hrv_baseline',
       'rhr_baseline', 'respiratory_rate', 'skin_temp_deviation',
       'calories_burned', 'workout_completed', 'activity_type',
       'activity_duration_min', 'activity_strain', 'avg_heart_rate',
       'max_heart_rate', 'activity_calories', 'hr_zone_1_min', 'hr_zone_2_min',
       'hr_zone_3_min', 'hr_zone_4_min', 'hr_zone_5_min',
       'workout_time_of_day'],
      dtype='object')

- wake_ups: The total number of times you wake up during the night after initially falling asleep.
- resting_heart_rate (RHR): Your heart rate measured while you are at complete rest, typically during your deepest sleep.
- rhr_baseline: The rolling average of your resting heart rate over a longer period (e.g., several weeks).
- respiratory_rate: The number of breaths you take per minute during sleep. 
- activity_strain: A score on a 0 to 21 scale that measures the amount of strain placed on heart and circulatory system during activity
- activity_calories: The estimated number of calories burned specifically during a recorded activity
- HR Zones : Is a 5-level intensity scale for heart. Instead of just giving you one average heart rate, it breaks your workout down into "buckets" of time to show how hard you were actually pushing.
- day_strain: This is your total cardiovascular load for the entire 24-hour period, measured on a logarithmic scale from 0 to 21. It includes not just your workouts, but also the stress of daily life
- recovery_score: A percentage from 0% to 100% that tells you how prepared your body is for the day.
- hrv: measures the variation in time between heart beats (e.g., one beat-to-beat interval might be seconds, the next).

In [138]:
df.nunique()

user_id                     286
date                        399
day_of_week                   7
age                          47
gender                        2
weight_kg                   224
height_cm                   188
fitness_level                 4
primary_sport                 8
recovery_score              879
day_strain                 2101
sleep_hours                 583
sleep_efficiency            501
sleep_performance             1
light_sleep_hours           383
rem_sleep_hours             160
deep_sleep_hours            133
wake_ups                      7
time_to_fall_asleep_min     289
hrv                        1296
resting_heart_rate          447
hrv_baseline                 86
rhr_baseline                 30
respiratory_rate            157
skin_temp_deviation         376
calories_burned            3831
workout_completed             2
activity_type                 9
activity_duration_min       103
activity_strain            2058
avg_heart_rate              769
max_heart_rate              806
activity_calories          1448
hr_zone_1_min               302
hr_zone_2_min               378
hr_zone_3_min               394
hr_zone_4_min               435
hr_zone_5_min               261
workout_time_of_day           3
dtype: int64

### droping constant feature "sleep_performance"

In [139]:


print(len(df.columns))
df = df.drop(columns=["sleep_performance"])
print(len(df.columns))

39
38

##  Feature Engineering

### 1.3. Creating the Injury Label (Injury Risk Proxy)

In [140]:
def create_injury_label(row):

    if row["day_strain"] > 15 and row["recovery_score"] < 40:
        return 1
    
    if row["recovery_score"] < 20 and row["hrv"] < 20:
        return 1
    
    if row["day_strain"] > 19:
        return 1
    return 0 


df['injury_label'] = df.apply(create_injury_label, axis=1)  # apply create_injury_label across each row in df
df

,user_id,date,day_of_week,age,gender,weight_kg,height_cm,fitness_level,primary_sport,recovery_score,...,avg_heart_rate,max_heart_rate,activity_calories,hr_zone_1_min,hr_zone_2_min,hr_zone_3_min,hr_zone_4_min,hr_zone_5_min,workout_time_of_day,injury_label
0,USER_00001,2023-01-01,Sunday,56,Female,53.9,167.2,Beginner,Weight Training,57.8,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0
1,USER_00001,2023-01-02,Monday,56,Female,53.9,167.2,Beginner,Weight Training,62.6,...,121.2,137.6,371.0,11.9,18.0,15.9,11.6,4.6,Evening,0
2,USER_00001,2023-01-03,Tuesday,56,Female,53.9,167.2,Beginner,Weight Training,81.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0
3,USER_00001,2023-01-04,Wednesday,56,Female,53.9,167.2,Beginner,Weight Training,55.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0
4,USER_00001,2023-01-05,Thursday,56,Female,53.9,167.2,Beginner,Weight Training,62.5,...,136.4,152.8,623.0,3.7,6.0,13.7,18.6,9.0,Evening,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,USER_00286,2023-05-13,Saturday,50,Female,58.9,153.9,Intermediate,Running,100.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0
99996,USER_00286,2023-05-14,Sunday,50,Female,58.9,153.9,Intermediate,Running,63.7,...,150.5,167.5,696.0,0.4,6.6,10.2,16.6,10.2,Evening,0
99997,USER_00286,2023-05-15,Monday,50,Female,58.9,153.9,Intermediate,Running,83.1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0
99998,USER_00286,2023-05-16,Tuesday,50,Female,58.9,153.9,Intermediate,Running,81.4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0
99999,USER_00286,2023-05-17,Wednesday,50,Female,58.9,153.9,Intermediate,Running,62.2,...,136.6,153.6,557.0,5.4,10.5,13.5,17.1,7.5,Morning,0

In [141]:
df.isna().sum()

user_id                        0
date                           0
day_of_week                    0
age                            0
gender                         0
weight_kg                      0
height_cm                      0
fitness_level                  0
primary_sport                  0
recovery_score                 0
day_strain                     0
sleep_hours                    0
sleep_efficiency               0
light_sleep_hours              0
rem_sleep_hours                0
deep_sleep_hours               0
wake_ups                       0
time_to_fall_asleep_min        0
hrv                            0
resting_heart_rate             0
hrv_baseline                   0
rhr_baseline                   0
respiratory_rate               0
skin_temp_deviation            0
calories_burned                0
workout_completed              0
activity_type                  0
activity_duration_min          0
activity_strain                0
avg_heart_rate                 0
max_heart_rate                 0
activity_calories              0
hr_zone_1_min                  0
hr_zone_2_min                  0
hr_zone_3_min                  0
hr_zone_4_min                  0
hr_zone_5_min                  0
workout_time_of_day        45990
injury_label                   0
dtype: int64

In [142]:

# sort data 
df = df.sort_values(['user_id', "date"])



# Lag Features: Create features from the previous days to capture trends.

windows = [7, 14, 28]
metrics = ['day_strain', 'hrv', 'sleep_hours', 'resting_heart_rate']

for window in windows:
    for metric in metrics:

        df[f"{metric}_roll_mean_{window}"] = df.groupby('user_id')[metric].transform(lambda x: x.rolling(window=window, min_periods=1).mean() )
        df[f"{metric}_roll_std_{window}"] = df.groupby('user_id')[metric].transform(lambda x: x.rolling(window=window, min_periods=1).std() )


# Rate of Change : Calculate the day-over-day change for key metrics.
for metric in metrics:
    df[f"{metric}_roc"] = df.groupby('user_id')[metric].pct_change()  # percentage rate of change
    df[f"{metric}_roc"] = df[f"{metric}_roc"].replace([np.inf, -np.inf, np.nan], 0)

df

,user_id,date,day_of_week,age,gender,weight_kg,height_cm,fitness_level,primary_sport,recovery_score,...,hrv_roll_mean_28,hrv_roll_std_28,sleep_hours_roll_mean_28,sleep_hours_roll_std_28,resting_heart_rate_roll_mean_28,resting_heart_rate_roll_std_28,day_strain_roc,hrv_roc,sleep_hours_roc,resting_heart_rate_roc
0,USER_00001,2023-01-01,Sunday,56,Female,53.9,167.2,Beginner,Weight Training,57.8,...,118.300000,NaN,6.130000,NaN,61.500000,NaN,0.000000,0.000000,0.000000,0.000000
1,USER_00001,2023-01-02,Monday,56,Female,53.9,167.2,Beginner,Weight Training,62.6,...,112.000000,8.909545,6.230000,0.141421,59.500000,2.828427,0.416098,-0.106509,0.032626,-0.065041
2,USER_00001,2023-01-03,Tuesday,56,Female,53.9,167.2,Beginner,Weight Training,81.5,...,106.433333,11.517523,6.210000,0.105830,58.566667,2.571640,-0.310212,-0.098392,-0.025276,-0.013913
3,USER_00001,2023-01-04,Wednesday,56,Female,53.9,167.2,Beginner,Weight Training,55.0,...,98.875000,17.803066,6.280000,0.164520,59.125000,2.378200,1.300279,-0.200420,0.051864,0.072310
4,USER_00001,2023-01-05,Thursday,56,Female,53.9,167.2,Beginner,Weight Training,62.5,...,97.980000,15.547251,6.358000,0.225211,60.420000,3.553449,0.012143,0.238845,0.027735,0.078947
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,USER_00286,2023-05-13,Saturday,50,Female,58.9,153.9,Intermediate,Running,100.0,...,101.178571,14.526639,8.073214,0.500067,50.617857,4.811333,0.147082,0.067393,0.121419,-0.159930
99996,USER_00286,2023-05-14,Sunday,50,Female,58.9,153.9,Intermediate,Running,63.7,...,100.496429,14.359498,8.081786,0.511186,50.560714,4.840672,-0.315679,-0.120706,0.074209,-0.008368
99997,USER_00286,2023-05-15,Monday,50,Female,58.9,153.9,Intermediate,Running,83.1,...,100.725000,14.433414,8.105357,0.490015,50.475000,4.935557,-0.122200,0.143611,-0.095130,-0.069620
99998,USER_00286,2023-05-16,Tuesday,50,Female,58.9,153.9,Intermediate,Running,81.4,...,100.396429,14.434847,8.101429,0.493068,50.607143,5.026591,0.938515,-0.114497,-0.038798,0.263039
99999,USER_00286,2023-05-17,Wednesday,50,Female,58.9,153.9,Intermediate,Running,62.2,...,99.664286,14.914999,8.119643,0.498951,50.378571,4.974108,-0.263315,-0.160584,0.109375,-0.131059

**Acute:Chronic Workload Ratio (ACWR)**:  
calculate the ratio of acute (7-day) to chronic (28-day) workload.

### Composite Strain Index

In [143]:
# Normalize each metric to 0-1 scale
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
df['strain_norm'] = scaler.fit_transform(df[['day_strain']])
df['hrv_inverse_norm'] = 1 - scaler.fit_transform(df[['hrv']])  # low HRV = high load
df['sleep_deficit_norm'] = 1 - scaler.fit_transform(df[['sleep_hours']]) / 8

# Composite load (weights based on domain knowledge)
df['daily_load'] = (0.6 * df['strain_norm'] + 
                     0.3 * df['hrv_inverse_norm'] + 
                     0.1 * df['sleep_deficit_norm'])

# Then compute ACWR on 'daily_load'
acute = df.groupby('user_id')['daily_load'].transform(lambda x: x.rolling(7, min_periods=1).mean())
chronic = df.groupby('user_id')['daily_load'].transform(lambda x: x.rolling(28, min_periods=1).mean())
df['acwr_composite'] = acute / (chronic + 1e-6)

df

,user_id,date,day_of_week,age,gender,weight_kg,height_cm,fitness_level,primary_sport,recovery_score,...,resting_heart_rate_roll_std_28,day_strain_roc,hrv_roc,sleep_hours_roc,resting_heart_rate_roc,strain_norm,hrv_inverse_norm,sleep_deficit_norm,daily_load,acwr_composite
0,USER_00001,2023-01-01,Sunday,56,Female,53.9,167.2,Beginner,Weight Training,57.8,...,NaN,0.000000,0.000000,0.000000,0.000000,0.349048,0.243846,0.955625,0.378145,0.999997
1,USER_00001,2023-01-02,Monday,56,Female,53.9,167.2,Beginner,Weight Training,62.6,...,2.828427,0.416098,-0.106509,0.032626,-0.065041,0.494286,0.340769,0.951458,0.493948,0.999998
2,USER_00001,2023-01-03,Tuesday,56,Female,53.9,167.2,Beginner,Weight Training,81.5,...,2.571640,-0.310212,-0.098392,-0.025276,-0.013913,0.340952,0.420769,0.954792,0.426281,0.999998
3,USER_00001,2023-01-04,Wednesday,56,Female,53.9,167.2,Beginner,Weight Training,55.0,...,2.378200,1.300279,-0.200420,0.051864,0.072310,0.784286,0.567692,0.948125,0.735692,0.999998
4,USER_00001,2023-01-05,Thursday,56,Female,53.9,167.2,Beginner,Weight Training,62.5,...,3.553449,0.012143,0.238845,0.027735,0.078947,0.793810,0.427692,0.944375,0.699031,0.999998
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,USER_00286,2023-05-13,Saturday,50,Female,58.9,153.9,Intermediate,Running,100.0,...,4.811333,0.147082,0.067393,0.121419,-0.159930,0.683333,0.325385,0.912083,0.598824,1.032089
99996,USER_00286,2023-05-14,Sunday,50,Female,58.9,153.9,Intermediate,Running,63.7,...,4.840672,-0.315679,-0.120706,0.074209,-0.008368,0.467619,0.425385,0.899375,0.498124,1.031622
99997,USER_00286,2023-05-15,Monday,50,Female,58.9,153.9,Intermediate,Running,83.1,...,4.935557,-0.122200,0.143611,-0.095130,-0.069620,0.410476,0.320769,0.916875,0.434204,1.006605
99998,USER_00286,2023-05-16,Tuesday,50,Female,58.9,153.9,Intermediate,Running,81.4,...,5.026591,0.938515,-0.114497,-0.038798,0.263039,0.795714,0.416154,0.923333,0.694608,1.044199
99999,USER_00286,2023-05-17,Wednesday,50,Female,58.9,153.9,Intermediate,Running,62.2,...,4.974108,-0.263315,-0.160584,0.109375,-0.131059,0.586190,0.534615,0.905833,0.602682,1.000089

In [144]:

df['date'] = pd.to_datetime(df['date'])

df['day_of_week'] = df['date'].dt.dayofweek  
df['month'] = df['date'].dt.month
df['day_of_month'] = df['date'].dt.day  
df['weekend'] = (df['date'].dt.dayofweek >= 5).astype(int)


# Cyclical encoding for day_of_week and month (important for tree models). December (11) and January (0) will have coordinates very close to each other on the circle. 
df['day_of_week_sin'] = np.sin(2 * np.pi * df['day_of_week'] / 7)
df['day_of_week_cos'] = np.cos(2 * np.pi * df['day_of_week'] / 7)
df['month_sin'] = np.sin(2 * np.pi * df['month'] / 12)
df['month_cos'] = np.cos(2 * np.pi * df['month'] / 12)


# Then drop the original 'date' column before training
df = df.drop(columns=['date'])
df

,user_id,day_of_week,age,gender,weight_kg,height_cm,fitness_level,primary_sport,recovery_score,day_strain,...,sleep_deficit_norm,daily_load,acwr_composite,month,day_of_month,weekend,day_of_week_sin,day_of_week_cos,month_sin,month_cos
0,USER_00001,6,56,Female,53.9,167.2,Beginner,Weight Training,57.8,7.33,...,0.955625,0.378145,0.999997,1,1,1,-0.781831,0.623490,0.5,0.866025
1,USER_00001,0,56,Female,53.9,167.2,Beginner,Weight Training,62.6,10.38,...,0.951458,0.493948,0.999998,1,2,0,0.000000,1.000000,0.5,0.866025
2,USER_00001,1,56,Female,53.9,167.2,Beginner,Weight Training,81.5,7.16,...,0.954792,0.426281,0.999998,1,3,0,0.781831,0.623490,0.5,0.866025
3,USER_00001,2,56,Female,53.9,167.2,Beginner,Weight Training,55.0,16.47,...,0.948125,0.735692,0.999998,1,4,0,0.974928,-0.222521,0.5,0.866025
4,USER_00001,3,56,Female,53.9,167.2,Beginner,Weight Training,62.5,16.67,...,0.944375,0.699031,0.999998,1,5,0,0.433884,-0.900969,0.5,0.866025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,USER_00286,5,50,Female,58.9,153.9,Intermediate,Running,100.0,14.35,...,0.912083,0.598824,1.032089,5,13,1,-0.974928,-0.222521,0.5,-0.866025
99996,USER_00286,6,50,Female,58.9,153.9,Intermediate,Running,63.7,9.82,...,0.899375,0.498124,1.031622,5,14,1,-0.781831,0.623490,0.5,-0.866025
99997,USER_00286,0,50,Female,58.9,153.9,Intermediate,Running,83.1,8.62,...,0.916875,0.434204,1.006605,5,15,0,0.000000,1.000000,0.5,-0.866025
99998,USER_00286,1,50,Female,58.9,153.9,Intermediate,Running,81.4,16.71,...,0.923333,0.694608,1.044199,5,16,0,0.781831,0.623490,0.5,-0.866025
99999,USER_00286,2,50,Female,58.9,153.9,Intermediate,Running,62.2,12.31,...,0.905833,0.602682,1.000089,5,17,0,0.974928,-0.222521,0.5,-0.866025

### categorical feature

In [145]:
# Replace 'N/A' with a new category, 'Unknown'

df['workout_time_of_day'] = df['workout_time_of_day'].fillna('Unknown')

In [146]:
# cyclic encoding of 'workout_time_of_day'

# First, map your categories to a numeric hour
time_map = {'Morning': 8, 'Afternoon': 14, 'Evening': 19, 'Unknown': 12}
df['hour_of_day'] = df['workout_time_of_day'].map(time_map)

# Apply cyclical encoding (sine/cosine transformation)
def encode_cyclical(data, col, max_val):
    data[f'{col}_sin'] = np.sin(2 * np.pi * data[col] / max_val)
    data[f'{col}_cos'] = np.cos(2 * np.pi * data[col] / max_val)
    return data

# Encode the hour (max_val is 24)
df = encode_cyclical(df, 'hour_of_day', 24)

# drop the intermediate 'hour_of_day' column
df = df.drop(columns=['hour_of_day', 'workout_time_of_day'])
df

,user_id,day_of_week,age,gender,weight_kg,height_cm,fitness_level,primary_sport,recovery_score,day_strain,...,acwr_composite,month,day_of_month,weekend,day_of_week_sin,day_of_week_cos,month_sin,month_cos,hour_of_day_sin,hour_of_day_cos
0,USER_00001,6,56,Female,53.9,167.2,Beginner,Weight Training,57.8,7.33,...,0.999997,1,1,1,-0.781831,0.623490,0.5,0.866025,1.224647e-16,-1.000000
1,USER_00001,0,56,Female,53.9,167.2,Beginner,Weight Training,62.6,10.38,...,0.999998,1,2,0,0.000000,1.000000,0.5,0.866025,-9.659258e-01,0.258819
2,USER_00001,1,56,Female,53.9,167.2,Beginner,Weight Training,81.5,7.16,...,0.999998,1,3,0,0.781831,0.623490,0.5,0.866025,1.224647e-16,-1.000000
3,USER_00001,2,56,Female,53.9,167.2,Beginner,Weight Training,55.0,16.47,...,0.999998,1,4,0,0.974928,-0.222521,0.5,0.866025,1.224647e-16,-1.000000
4,USER_00001,3,56,Female,53.9,167.2,Beginner,Weight Training,62.5,16.67,...,0.999998,1,5,0,0.433884,-0.900969,0.5,0.866025,-9.659258e-01,0.258819
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,USER_00286,5,50,Female,58.9,153.9,Intermediate,Running,100.0,14.35,...,1.032089,5,13,1,-0.974928,-0.222521,0.5,-0.866025,1.224647e-16,-1.000000
99996,USER_00286,6,50,Female,58.9,153.9,Intermediate,Running,63.7,9.82,...,1.031622,5,14,1,-0.781831,0.623490,0.5,-0.866025,-9.659258e-01,0.258819
99997,USER_00286,0,50,Female,58.9,153.9,Intermediate,Running,83.1,8.62,...,1.006605,5,15,0,0.000000,1.000000,0.5,-0.866025,1.224647e-16,-1.000000
99998,USER_00286,1,50,Female,58.9,153.9,Intermediate,Running,81.4,16.71,...,1.044199,5,16,0,0.781831,0.623490,0.5,-0.866025,1.224647e-16,-1.000000
99999,USER_00286,2,50,Female,58.9,153.9,Intermediate,Running,62.2,12.31,...,1.000089,5,17,0,0.974928,-0.222521,0.5,-0.866025,8.660254e-01,-0.500000

In [147]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 79 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   user_id                          100000 non-null  object
 1   day_of_week                      100000 non-null  int32
 2   age                              100000 non-null  int64
 3   gender                           100000 non-null  object
 4   weight_kg                        100000 non-null  float64
 5   height_cm                        100000 non-null  float64
 6   fitness_level                    100000 non-null  object
 7   primary_sport                    100000 non-null  object
 8   recovery_score                   100000 non-null  float64
 9   day_strain                       100000 non-null  float64
 10  sleep_hours                      100000 non-null  float64
 11  sleep_efficiency                 100000 non-null  float64
 12  light_sleep_hours                100000 non-null  float64
 13  rem_sleep_hours                  100000 non-null  float64
 14  deep_sleep_hours                 100000 non-null  float64
 15  wake_ups                         100000 non-null  int64
 16  time_to_fall_asleep_min          100000 non-null  float64
 17  hrv                              100000 non-null  float64
 18  resting_heart_rate               100000 non-null  float64
 19  hrv_baseline                     100000 non-null  int64
 20  rhr_baseline                     100000 non-null  int64
 21  respiratory_rate                 100000 non-null  float64
 22  skin_temp_deviation              100000 non-null  float64
 23  calories_burned                  100000 non-null  float64
 24  workout_completed                100000 non-null  int64
 25  activity_type                    100000 non-null  object
 26  activity_duration_min            100000 non-null  int64
 27  activity_strain                  100000 non-null  float64
 28  avg_heart_rate                   100000 non-null  float64
 29  max_heart_rate                   100000 non-null  float64
 30  activity_calories                100000 non-null  float64
 31  hr_zone_1_min                    100000 non-null  float64
 32  hr_zone_2_min                    100000 non-null  float64
 33  hr_zone_3_min                    100000 non-null  float64
 34  hr_zone_4_min                    100000 non-null  float64
 35  hr_zone_5_min                    100000 non-null  float64
 36  injury_label                     100000 non-null  int64
 37  day_strain_roll_mean_7           100000 non-null  float64
 38  day_strain_roll_std_7            99714 non-null   float64
 39  hrv_roll_mean_7                  100000 non-null  float64
 40  hrv_roll_std_7                   99714 non-null   float64
 41  sleep_hours_roll_mean_7          100000 non-null  float64
 42  sleep_hours_roll_std_7           99714 non-null   float64
 43  resting_heart_rate_roll_mean_7   100000 non-null  float64
 44  resting_heart_rate_roll_std_7    99714 non-null   float64
 45  day_strain_roll_mean_14          100000 non-null  float64
 46  day_strain_roll_std_14           99714 non-null   float64
 47  hrv_roll_mean_14                 100000 non-null  float64
 48  hrv_roll_std_14                  99714 non-null   float64
 49  sleep_hours_roll_mean_14         100000 non-null  float64
 50  sleep_hours_roll_std_14          99714 non-null   float64
 51  resting_heart_rate_roll_mean_14  100000 non-null  float64
 52  resting_heart_rate_roll_std_14   99714 non-null   float64
 53  day_strain_roll_mean_28          100000 non-null  float64
 54  day_strain_roll_std_28           99714 non-null   float64
 55  hrv_roll_mean_28                 100000 non-null  float64
 56  hrv_roll_std_28                  99714 non-null   float64
 57  sleep_hours_roll_mean_28         100000 non-null  float64
 58  sleep_hours_roll_std_28          99714 non-null   float64
 59  resting_heart_rate_roll_mean_28  100000 non-null  float64
 60  resting_heart_rate_roll_std_28   99714 non-null   float64
 61  day_strain_roc                   100000 non-null  float64
 62  hrv_roc                          100000 non-null  float64
 63  sleep_hours_roc                  100000 non-null  float64
 64  resting_heart_rate_roc           100000 non-null  float64
 65  strain_norm                      100000 non-null  float64
 66  hrv_inverse_norm                 100000 non-null  float64
 67  sleep_deficit_norm               100000 non-null  float64
 68  daily_load                       100000 non-null  float64
 69  acwr_composite                   100000 non-null  float64
 70  month                            100000 non-null  int32
 71  day_of_month                     100000 non-null  int32
 72  weekend                          100000 non-null  int64
 73  day_of_week_sin                  100000 non-null  float64
 74  day_of_week_cos                  100000 non-null  float64
 75  month_sin                        100000 non-null  float64
 76  month_cos                        100000 non-null  float64
 77  hour_of_day_sin                  100000 non-null  float64
 78  hour_of_day_cos                  100000 non-null  float64
dtypes: float64(63), int32(3), int64(8), object(5)
memory usage: 59.1+ MB

In [148]:
# Identify categorical columns and label encoding performing

from sklearn.preprocessing import LabelEncoder
categorical_cols = ['gender', 'fitness_level', 'primary_sport', 'activity_type']

# Label encode each

for col in categorical_cols:
   
    df[col] = df[col].astype('category')
    

df

,user_id,day_of_week,age,gender,weight_kg,height_cm,fitness_level,primary_sport,recovery_score,day_strain,...,acwr_composite,month,day_of_month,weekend,day_of_week_sin,day_of_week_cos,month_sin,month_cos,hour_of_day_sin,hour_of_day_cos
0,USER_00001,6,56,Female,53.9,167.2,Beginner,Weight Training,57.8,7.33,...,0.999997,1,1,1,-0.781831,0.623490,0.5,0.866025,1.224647e-16,-1.000000
1,USER_00001,0,56,Female,53.9,167.2,Beginner,Weight Training,62.6,10.38,...,0.999998,1,2,0,0.000000,1.000000,0.5,0.866025,-9.659258e-01,0.258819
2,USER_00001,1,56,Female,53.9,167.2,Beginner,Weight Training,81.5,7.16,...,0.999998,1,3,0,0.781831,0.623490,0.5,0.866025,1.224647e-16,-1.000000
3,USER_00001,2,56,Female,53.9,167.2,Beginner,Weight Training,55.0,16.47,...,0.999998,1,4,0,0.974928,-0.222521,0.5,0.866025,1.224647e-16,-1.000000
4,USER_00001,3,56,Female,53.9,167.2,Beginner,Weight Training,62.5,16.67,...,0.999998,1,5,0,0.433884,-0.900969,0.5,0.866025,-9.659258e-01,0.258819
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,USER_00286,5,50,Female,58.9,153.9,Intermediate,Running,100.0,14.35,...,1.032089,5,13,1,-0.974928,-0.222521,0.5,-0.866025,1.224647e-16,-1.000000
99996,USER_00286,6,50,Female,58.9,153.9,Intermediate,Running,63.7,9.82,...,1.031622,5,14,1,-0.781831,0.623490,0.5,-0.866025,-9.659258e-01,0.258819
99997,USER_00286,0,50,Female,58.9,153.9,Intermediate,Running,83.1,8.62,...,1.006605,5,15,0,0.000000,1.000000,0.5,-0.866025,1.224647e-16,-1.000000
99998,USER_00286,1,50,Female,58.9,153.9,Intermediate,Running,81.4,16.71,...,1.044199,5,16,0,0.781831,0.623490,0.5,-0.866025,1.224647e-16,-1.000000
99999,USER_00286,2,50,Female,58.9,153.9,Intermediate,Running,62.2,12.31,...,1.000089,5,17,0,0.974928,-0.222521,0.5,-0.866025,8.660254e-01,-0.500000

In [134]:
df['injury_label']
df['injury_label'] = df.groupby('user_id')['injury_label'].shift(-1)
df['injury_label']

0        0.0
1        0.0
2        0.0
3        0.0
4        0.0
        ...
99995    0.0
99996    0.0
99997    0.0
99998    0.0
99999    NaN
Name: injury_label, Length: 100000, dtype: float64

In [120]:
print(df['injury_label'].isna().sum())
df = df.dropna()
df['injury_label'].isna().sum()
df['injury_label']

0

1        0.0
2        0.0
3        0.0
4        0.0
5        0.0
        ...
99995    0.0
99996    0.0
99997    0.0
99998    0.0
99999    0.0
Name: injury_label, Length: 99714, dtype: float64

In [184]:
X = df.drop(columns=['injury_label'])
y = df['injury_label']
y

0        0
1        0
2        0
3        0
4        0
        ..
99995    0
99996    0
99997    0
99998    0
99999    0
Name: injury_label, Length: 100000, dtype: int64

##  Model Training

In [185]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42, stratify=y)

neg_count = (y_train == 0).sum()
pos_count = (y_train == 1).sum()

scale_pos_weight = neg_count / pos_count

print(f"Negative: {neg_count}, Positive: {pos_count}, Ratio: {scale_pos_weight:.2f}")

Negative: 86501, Positive: 3499, Ratio: 24.72

In [186]:
import optuna
from sklearn.model_selection import GroupKFold, cross_val_score
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier


def cv_score(model, X, y, cv_folds=5):
    
    gkf = GroupKFold(n_splits=cv_folds)
    groups = X['user_id']
    X = X.drop(columns=['user_id'])
    scores = cross_val_score(estimator=model, X=X, y=y, cv=gkf, groups=groups, scoring='neg_root_mean_squared_error')  
    return -scores.mean()


def objective_xgb(trial, X, y, cv_folds):
    params = {
        'n_estimators': trial.suggest_int('n_estimators', 50, 350, step=50),
        'max_depth': trial.suggest_int('max_depth', 1, 15),
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3, log=True),
        'subsample': trial.suggest_float('subsample', 0.5, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.5, 1.0),
        'min_child_weight': trial.suggest_int('min_child_weight', 1, 15),
        'gamma': trial.suggest_float('gamma', 0, 5),
        'reg_alpha': trial.suggest_float('reg_alpha', 1e-8, 10.0, log=True),
        'reg_lambda': trial.suggest_float('reg_lambda', 1e-3, 10.0, log=True),
        "tree_method": "hist",  
        "device": "cuda",
    }
    
    model = XGBClassifier(**params, random_state=42, verbosity=0, scale_pos_weight=scale_pos_weight)
    score = cross_val_score(model, X, y, cv_folds=cv_folds)

    return score.mean() 


def objective_lgbm(trial, X, y, cv_folds):
    params = {
        'n_estimators': trial.suggest_int('n_estimators', 50, 350, step=50),
        'max_depth': trial.suggest_int('max_depth', 1, 10),
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3, log=True),
        'bagging_fraction': trial.suggest_float('bagging_fraction', 0.5, 1.0),
        'feature_fraction': trial.suggest_float('feature_fraction', 0.5, 1.0),
        'min_child_samples': trial.suggest_int('min_child_samples', 1, 100),
        'reg_alpha': trial.suggest_float('reg_alpha', 1e-8, 10.0, log=True),
        'reg_lambda': trial.suggest_float('reg_lambda', 1e-4, 10.0, log=True),
        'num_leaves': trial.suggest_int('num_leaves', 10, 100),
        'min_split_gain': trial.suggest_float('min_split_gain', 0, 1),
        "device": "gpu"            
    }

    model = LGBMClassifier(**params, random_state=42, verbose=-1, scale_pos_weight=scale_pos_weight)
    score = cv_score(model, X, y, cv_folds)
    return score.mean()

In [ ]:
def tune_with_optuna(X_train, y_train, model_name, n_trials=50):

    X = X_train
    y = y_train
    
    objectives ={
        "XGBoost": objective_xgb,
        "LightGBM": objective_lgbm
    }

    study = optuna.create_study(direction='minimize', sampler=optuna.samplers.TPESampler(seed=42))

    study.optimize(lambda trail: objectives[model_name](trial=trail, X=X, y=y, cv_folds=5), 
                   n_trials=n_trials, show_progress_bar=True, n_jobs=-1)

    best_params = study.best_params
    best_rmse = study.best_value
    
    print(f"Best params: {best_params} -- Best rmse: {best_rmse}")

tune_with_optuna(X_train, y_train, model_name="LightGBM")

[I 2026-04-15 17:23:46,628] A new study created in memory with name: no-name-49dcbffa-ab26-4fdd-835e-2d9201a53b02

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-04-15 17:24:13,283] Trial 2 finished with value: 0.12042025708408773 and parameters: {'n_estimators': 50, 'max_depth': 1, 'learning_rate': 0.031011692772612166, 'bagging_fraction': 0.8871312746348884, 'feature_fraction': 0.8696855181810853, 'min_child_samples': 76, 'reg_alpha': 5.732594655653799e-07, 'reg_lambda': 0.004107858298766563, 'num_leaves': 32, 'min_split_gain': 0.2060723986779519}. Best is trial 2 with value: 0.12042025708408773.
[I 2026-04-15 17:24:48,611] Trial 10 finished with value: 0.04305933359284285 and parameters: {'n_estimators': 250, 'max_depth': 1, 'learning_rate': 0.14272229295539732, 'bagging_fraction': 0.6816800419981651, 'feature_fraction': 0.8440492098594683, 'min_child_samples': 42, 'reg_alpha': 2.9584259544569635e-06, 'reg_lambda': 0.0018902848358643301, 'num_leaves': 37, 'min_split_gain': 0.21866505858751517}. Best is trial 10 with value: 0.04305933359284285.
[I 2026-04-15 17:24:56,153] Trial 12 finished with value: 0.04305933359284285 and parameters: {'n_estimators': 100, 'max_depth': 7, 'learning_rate': 0.02355190409862393, 'bagging_fraction': 0.9208395510496981, 'feature_fraction': 0.8809592889416313, 'min_child_samples': 99, 'reg_alpha': 3.642671981144598e-07, 'reg_lambda': 0.15859916049848724, 'num_leaves': 15, 'min_split_gain': 0.637747044592376}. Best is trial 10 with value: 0.04305933359284285.
[I 2026-04-15 17:25:08,201] Trial 15 finished with value: 0.04318972347102444 and parameters: {'n_estimators': 100, 'max_depth': 5, 'learning_rate': 0.04348628591585797, 'bagging_fraction': 0.583952498190016, 'feature_fraction': 0.5165840402439372, 'min_child_samples': 56, 'reg_alpha': 0.5607475829559377, 'reg_lambda': 0.011726224640847297, 'num_leaves': 88, 'min_split_gain': 0.2182540586893419}. Best is trial 10 with value: 0.04305933359284285.
[I 2026-04-15 17:25:10,730] Trial 16 finished with value: 0.0423968882909298 and parameters: {'n_estimators': 100, 'max_depth': 4, 'learning_rate': 0.17791566649660015, 'bagging_fraction': 0.6393463583681089, 'feature_fraction': 0.658502071856672, 'min_child_samples': 74, 'reg_alpha': 5.1440019145895395, 'reg_lambda': 0.0033002505536819985, 'num_leaves': 22, 'min_split_gain': 0.48600252209608397}. Best is trial 16 with value: 0.0423968882909298.
[I 2026-04-15 17:25:18,022] Trial 7 finished with value: 0.04305933359284285 and parameters: {'n_estimators': 100, 'max_depth': 7, 'learning_rate': 0.017885818705974405, 'bagging_fraction': 0.9220382891632194, 'feature_fraction': 0.6938876142903859, 'min_child_samples': 47, 'reg_alpha': 0.034455357734702555, 'reg_lambda': 0.007333341957404975, 'num_leaves': 87, 'min_split_gain': 0.8789803999879218}. Best is trial 16 with value: 0.0423968882909298.
[I 2026-04-15 17:25:34,376] Trial 4 finished with value: 0.042792292331490685 and parameters: {'n_estimators': 200, 'max_depth': 4, 'learning_rate': 0.025578327147433747, 'bagging_fraction': 0.57705272635369, 'feature_fraction': 0.788104759042636, 'min_child_samples': 70, 'reg_alpha': 7.289845716608906e-07, 'reg_lambda': 0.055553838592736965, 'num_leaves': 68, 'min_split_gain': 0.03214592781377368}. Best is trial 16 with value: 0.0423968882909298.
[I 2026-04-15 17:25:34,537] Trial 1 finished with value: 0.042792292331490685 and parameters: {'n_estimators': 200, 'max_depth': 3, 'learning_rate': 0.018853364188075237, 'bagging_fraction': 0.6147906705276475, 'feature_fraction': 0.8876769442571009, 'min_child_samples': 47, 'reg_alpha': 8.957421755624608e-07, 'reg_lambda': 0.13552815198403956, 'num_leaves': 75, 'min_split_gain': 0.6426477773266848}. Best is trial 16 with value: 0.0423968882909298.
[I 2026-04-15 17:25:52,015] Trial 0 finished with value: 0.04305933359284285 and parameters: {'n_estimators': 200, 'max_depth': 10, 'learning_rate': 0.010035913460071069, 'bagging_fraction': 0.7895122574222998, 'feature_fraction': 0.9825333179046023, 'min_child_samples': 51, 'reg_alpha': 0.004713340185337732, 'reg_lambda': 0.07200486828610395, 'num_leaves': 27, 'min_split_gain': 0.5890081073171469}. Best is trial 16 with value: 0.0423968882909298.
[I 2026-04-15 17:26:00,370] Trial 5 finished with value: 0.042792292331490685 and parameters: {'n_estimators': 200, 'max_depth': 5, 'learning_rate': 0.024486583717490237, 'bagging_fraction': 0.7332291960296398, 'feature_fraction': 0.6336531525960478, 'min_child_samples': 44, 'reg_alpha': 9.180843140030133e-06, 'reg_lambda': 0.23018627997391536, 'num_leaves': 59, 'min_split_gain': 0.9457762684971373}. Best is trial 16 with value: 0.0423968882909298.
[I 2026-04-15 17:26:09,360] Trial 22 finished with value: 0.04318972347102444 and parameters: {'n_estimators': 50, 'max_depth': 3, 'learning_rate': 0.1504404593612276, 'bagging_fraction': 0.6091143672094916, 'feature_fraction': 0.8738896377672036, 'min_child_samples': 68, 'reg_alpha': 0.017530999453394328, 'reg_lambda': 1.2950493411496407, 'num_leaves': 41, 'min_split_gain': 0.07309911370600264}. Best is trial 16 with value: 0.0423968882909298.
[I 2026-04-15 17:26:15,183] Trial 6 finished with value: 0.04241832206952394 and parameters: {'n_estimators': 200, 'max_depth': 5, 'learning_rate': 0.04177626743328942, 'bagging_fraction': 0.628353060430811, 'feature_fraction': 0.6427299689363155, 'min_child_samples': 99, 'reg_alpha': 1.6619400211943282e-05, 'reg_lambda': 0.8517322637842496, 'num_leaves': 72, 'min_split_gain': 0.7922396791096493}. Best is trial 16 with value: 0.0423968882909298.
[I 2026-04-15 17:26:22,083] Trial 9 finished with value: 0.042792292331490685 and parameters: {'n_estimators': 150, 'max_depth': 10, 'learning_rate': 0.011023137017335668, 'bagging_fraction': 0.8316534246196126, 'feature_fraction': 0.6803391943930368, 'min_child_samples': 98, 'reg_alpha': 3.1548529504816124e-07, 'reg_lambda': 0.4582575573794307, 'num_leaves': 42, 'min_split_gain': 0.3793949602952523}. Best is trial 16 with value: 0.0423968882909298.
[I 2026-04-15 17:26:40,399] Trial 17 finished with value: 0.04155099693719968 and parameters: {'n_estimators': 200, 'max_depth': 4, 'learning_rate': 0.14297433677198024, 'bagging_fraction': 0.5973021188587844, 'feature_fraction': 0.5156019218028436, 'min_child_samples': 29, 'reg_alpha': 6.418978418119935e-05, 'reg_lambda': 1.6372890292091955, 'num_leaves': 94, 'min_split_gain': 0.9107986710217875}. Best is trial 17 with value: 0.04155099693719968.
[I 2026-04-15 17:26:54,765] Trial 14 finished with value: 0.04195728262786204 and parameters: {'n_estimators': 200, 'max_depth': 6, 'learning_rate': 0.06944753891997414, 'bagging_fraction': 0.8146193668481145, 'feature_fraction': 0.6532613188821663, 'min_child_samples': 37, 'reg_alpha': 0.022229462370112828, 'reg_lambda': 0.010745154875223876, 'num_leaves': 52, 'min_split_gain': 0.660952360472475}. Best is trial 17 with value: 0.04155099693719968.
[I 2026-04-15 17:26:57,476] Trial 8 finished with value: 0.04230005043401759 and parameters: {'n_estimators': 250, 'max_depth': 5, 'learning_rate': 0.02090973070431674, 'bagging_fraction': 0.7530801195207792, 'feature_fraction': 0.8356853624660545, 'min_child_samples': 5, 'reg_alpha': 2.6941556137465844e-06, 'reg_lambda': 0.41043549666227264, 'num_leaves': 47, 'min_split_gain': 0.41112952393090463}. Best is trial 17 with value: 0.04155099693719968.
[I 2026-04-15 17:27:02,021] Trial 20 finished with value: 0.04297665365517047 and parameters: {'n_estimators': 250, 'max_depth': 6, 'learning_rate': 0.15243958397205362, 'bagging_fraction': 0.963883534169006, 'feature_fraction': 0.5592113284813282, 'min_child_samples': 27, 'reg_alpha': 3.0698832916949e-07, 'reg_lambda': 0.0010855767956273294, 'num_leaves': 84, 'min_split_gain': 0.35265387656174196}. Best is trial 17 with value: 0.04155099693719968.